
from logikbench import *

basic_list = [Arbiter(),
              Band(),
              Bbuf(),
              Bin2gray(),
              Bin2prio(),
              Binv(),
              Bnand(),
              Bnor(),
              Bor(),
              Bxnor(),
              Bxor(),
              Crossbar(),
              Dffasync(),
              Dffsync(),
              Gray2bin(),
              Mux(),
              Muxcase(),
              Muxhot(),
              Muxpri(),
              Onehot(),
              Pipeline(),
              Shiftreg()]

memory_list = [Cache(),
               Fifoasync(),
               Fifosync(),
               Ramasync(),
               Rambit(),
               Rambyte(),
               Ramdp(),
               Ramsdp(),
               Ramsp(),
               Ramspnc(),
               Regfile(),
               Rom()]

arithmetic_list = [Abs(),
                   Absdiff(),
                   Absdiffs(),
                   Add(),
                   Addsub(),
                   Cmp(),
                   Counter(),
                   Csa32(),
                   Csa42(),
                   Dec(),
                   Dotprod(),
                   Inc(),
                   Log2(),
                   Mac(),
                   Max(),
                   Min(),
                   Mul(),
                   Muladd(),
                   Muladdc(),
                   Mulc(),
                   Mulreg(),
                   Muls(),
                   Relu(),
                   Round(),
                   Shiftar(),
                   Shiftb(),
                   Shiftl(),
                   Shiftr(),
                   Sine(),
                   Sqdiff(),
                   Sqrt(),
                   Sub(),
                   Sum()]

block_list = [Aes(),
              Axicrossbar(),
              Ethmac(),
              Ialu(),
              I2c(),
              Lfsr(),
              Picorv32(),
              Serv(),
              Uart()]
