
from logikbench import *

basic_list = [basic.Arbiter(),
              basic.Band(),
              basic.Bbuf(),
              basic.Bin2gray(),
              basic.Bin2prio(),
              basic.Binv(),
              basic.Bnand(),
              basic.Bnor(),
              basic.Bor(),
              basic.Bxnor(),
              basic.Bxor(),
              basic.Crossbar(),
              basic.Dffasync(),
              basic.Dffsync(),
              basic.Gray2bin(),
              basic.Mux(),
              basic.Muxcase(),
              basic.Muxhot(),
              basic.Muxpri(),
              basic.Onehot(),
              basic.Pipeline(),
              basic.Shiftreg()]

memory_list = [memory.Cache(),
               memory.Fifoasync(),
               memory.Fifosync(),
               memory.Ramasync(),
               memory.Rambit(),
               memory.Rambyte(),
               memory.Ramdp(),
               memory.Ramsdp(),
               memory.Ramsp(),
               memory.Ramspnc(),
               memory.Regfile(),
               memory.Rom()]

arithmetic_list = [arithmetic.Abs(),
                   arithmetic.Absdiff(),
                   arithmetic.Absdiffs(),
                   arithmetic.Add(),
                   arithmetic.Addsub(),
                   arithmetic.Cmp(),
                   arithmetic.Counter(),
                   arithmetic.Csa32(),
                   arithmetic.Csa42(),
                   arithmetic.Dec(),
                   arithmetic.Dotprod(),
                   arithmetic.Inc(),
                   arithmetic.Log2(),
                   arithmetic.Mac(),
                   arithmetic.Max(),
                   arithmetic.Min(),
                   arithmetic.Mul(),
                   arithmetic.Muladd(),
                   arithmetic.Muladdc(),
                   arithmetic.Mulc(),
                   arithmetic.Mulreg(),
                   arithmetic.Muls(),
                   arithmetic.Relu(),
                   arithmetic.Round(),
                   arithmetic.Shiftar(),
                   arithmetic.Shiftb(),
                   arithmetic.Shiftl(),
                   arithmetic.Shiftr(),
                   arithmetic.Sine(),
                   arithmetic.Sqdiff(),
                   arithmetic.Sqrt(),
                   arithmetic.Sub(),
                   arithmetic.Sum()]

block_list = [blocks.Aes(),
              blocks.Axicrossbar(),
              blocks.Ethmac(),
              blocks.Firfix(),
              blocks.Firprog(),
              blocks.Ialu(),
              blocks.I2c(),
              blocks.Lfsr(),
              blocks.Picorv32(),
              blocks.Serv(),
              blocks.Uart()]
