#!/usr/bin/env python3
# Generator for a static canonical Huffman codec (huffman_enc.v / huffman_dec.v).
# Builds a real canonical Huffman code from a frequency distribution and emits
# the code/length ROMs (encoder) and the per-length count + symbol-order ROMs
# (decoder, puff-style canonical decode). Tables are emitted as synthesizable
# combinational 'case' ROMs (no functions, no initial blocks; survive
# --ignore-initial). Reindent the emitted .v with emacs verilog-mode.
import heapq

NSYM = 256
MAXLEN = 15


def huffman_lengths(freq):
    # standard Huffman -> code length per symbol
    heap = [[f, [s]] for s, f in enumerate(freq)]
    heapq.heapify(heap)
    length = [0] * NSYM
    while len(heap) > 1:
        a = heapq.heappop(heap)
        b = heapq.heappop(heap)
        for s in a[1] + b[1]:
            length[s] += 1
        heapq.heappush(heap, [a[0] + b[0], a[1] + b[1]])
    return length


def canonical(length):
    cnt = [0] * (MAXLEN + 1)
    for s in range(NSYM):
        cnt[length[s]] += 1
    # canonical codes, assigned in (length, symbol-value) order
    first = [0] * (MAXLEN + 2)
    for L in range(1, MAXLEN + 1):
        first[L] = (first[L - 1] + cnt[L - 1]) << 1
    nextc = first[:]
    code = [0] * NSYM
    for s in range(NSYM):
        L = length[s]
        if L:
            code[s] = nextc[L]
            nextc[L] += 1
    # decoder symbol order: sorted by (length, value)
    order = sorted(range(NSYM), key=lambda s: (length[s], s))
    return cnt, code, order


def emit_enc(length, code, maxlen):
    # one combinational case ROM keyed on in_sym, driving both regs at once
    rom = "\n".join(
        "        8'd%d: begin enc_len_r = 4'd%d; enc_code_r = 15'd%d; end"
        % (s, length[s], code[s]) for s in range(NSYM))
    return ENC_TMPL.replace("//ENCROM//", rom).replace("//MAXLEN//", str(maxlen))


def emit_dec(cnt, order, maxlen):
    crom = "\n".join("        4'd%d: cnt_r = 9'd%d;" % (L, cnt[L])
                     for L in range(1, MAXLEN + 1))
    srom = "\n".join("        8'd%d: dsym_r = 8'd%d;" % (i, s)
                     for i, s in enumerate(order))
    return (DEC_TMPL.replace("//CNTROM//", crom).replace("//SYMROM//", srom)
            .replace("//MAXLEN//", str(maxlen)))


ENC_TMPL = r'''//#############################################################################
// Copyright: Zero ASIC. All rights Reserved.
// License:  MIT (see LICENSE file in LogikBench repository)
//#############################################################################
//
// Static canonical Huffman ENCODER (8-bit symbols). Per-symbol canonical code
// and length come from a baked-in ROM (generated by genhuff.py). A bit-packer
// concatenates the variable-length codes (MSB first) and emits output bytes.
// Streaming with valid/ready; in_last flushes the final partial byte.
//
// Generated by genhuff.py.
//
//#############################################################################

module huffman_enc
  (
   input            clk,
   input            rst,
   input            in_valid,
   input [7:0]      in_sym,
   input            in_last,
   output           in_ready,
   output           out_valid,
   output [7:0]     out_byte,
   output           out_last,
   input            out_ready
   );

   localparam ACCW = 24;

   reg [ACCW-1:0] acc;     // bit accumulator, valid bits right-justified
   reg [4:0]      nbits;   // number of valid bits in acc
   reg            flush;   // draining the final frame

   //##########################################################################
   // Canonical Huffman code table (generated by genhuff.py)
   //
   // 256 8-bit symbols. The code is a canonical Huffman code built for the
   // frequency model freq[s] = round(1e6 * 0.98^s), s = 0..255 -- a geometric
   // distribution where smaller symbol values are more frequent and so get
   // shorter codes. Max code length = //MAXLEN// bits (cap 15).
   //
   //   enc_len_r  : code length in bits for in_sym
   //   enc_code_r : canonical code for in_sym, right-justified; the encoder
   //                emits the low enc_len_r bits MSB-first
   //##########################################################################
   reg [3:0]  enc_len_r;
   reg [14:0] enc_code_r;
   always @* begin
      case (in_sym)
//ENCROM//
        default: begin enc_len_r = 4'd0; enc_code_r = 15'd0; end
      endcase
   end

   wire [3:0]  clen  = enc_len_r;
   wire [14:0] ccode = enc_code_r;

   // combinational valid/ready producer (a byte transfers only when both
   // out_valid and out_ready are high in the same cycle)
   wire byte_avail = (nbits >= 8);
   wire flush_byte = flush && (nbits > 0) && (nbits < 8);
   assign out_valid = byte_avail | flush_byte;
   assign out_byte  = byte_avail ? acc[nbits-1 -: 8] : (acc[7:0] << (8 - nbits));
   assign out_last  = flush_byte;
   assign in_ready  = !flush && (nbits < 8);

   always @(posedge clk) begin
      if (rst) begin
         acc <= 0; nbits <= 0; flush <= 1'b0;
      end
      else if (out_valid && out_ready) begin
         if (byte_avail) nbits <= nbits - 5'd8;   // full byte sent
         else begin nbits <= 0; flush <= 1'b0; end // final partial byte sent
      end
      else if (in_valid && in_ready) begin
         acc   <= (acc << clen) | {{(ACCW-15){1'b0}}, ccode};
         nbits <= nbits + clen;
         if (in_last) flush <= 1'b1;
      end
      else if (flush && (nbits == 0)) begin
         flush <= 1'b0;                            // frame ended on a boundary
      end
   end

endmodule
'''


DEC_TMPL = r'''//#############################################################################
// Copyright: Zero ASIC. All rights Reserved.
// License:  MIT (see LICENSE file in LogikBench repository)
//#############################################################################
//
// Static canonical Huffman DECODER (8-bit symbols). Bit-serial canonical
// decode (puff-style): per code length L, codes of that length occupy a
// contiguous range; cnt[L] and the symbol-order ROM (generated by genhuff.py)
// drive the decode. Streaming: bytes in (valid/ready), symbols out (valid).
//
// Generated by genhuff.py.
//
//#############################################################################

module huffman_dec
  (
   input            clk,
   input            rst,
   input            in_valid,
   input [7:0]      in_byte,
   output           in_ready,
   output reg       out_valid,
   output reg [7:0] out_sym
   );

   localparam MAXLEN = 15;

   // bit buffer: up to 16 bits, valid bits left-justified (MSB first)
   reg [15:0] bitbuf;
   reg [4:0]  navail;

   // puff decode state
   reg [15:0] code;
   reg [15:0] first;
   reg [8:0]  index;
   reg [3:0]  len;

   assign in_ready = (navail <= 8);

   wire        have_bit = (navail > 0);
   wire        next_bit = bitbuf[15];                // MSB of valid field
   wire [15:0] code1    = code | {15'b0, next_bit};  // add bit (no pre-shift)

   //##########################################################################
   // Canonical Huffman decode tables (generated by genhuff.py)
   //
   // Same canonical code as huffman_enc: 256 8-bit symbols, frequency model
   // freq[s] = round(1e6 * 0.98^s), max code length //MAXLEN// bits. Puff-style
   // canonical decode needs only:
   //   cnt_r  : number of codewords of length 'len' (per-length count)
   //   dsym_r : symbol at canonical index 'symidx' (symbols sorted by code
   //            length, then by symbol value)
   //##########################################################################
   reg [8:0] cnt_r;
   always @* begin
      case (len)
//CNTROM//
        default: cnt_r = 9'd0;
      endcase
   end

   wire [8:0] count  = cnt_r;
   wire       match  = (code1 < (first + count));
   wire [7:0] symidx = index + (code1 - first);

   reg [7:0] dsym_r;
   always @* begin
      case (symidx)
//SYMROM//
        default: dsym_r = 8'd0;
      endcase
   end

   always @(posedge clk) begin
      if (rst) begin
         bitbuf <= 0; navail <= 0;
         code <= 0; first <= 0; index <= 0; len <= 4'd1;
         out_valid <= 1'b0; out_sym <= 8'b0;
      end
      else begin
         out_valid <= 1'b0;
         if (in_valid && in_ready) begin
            // append the incoming byte below the current valid field
            bitbuf <= bitbuf | ({8'b0, in_byte} << (8 - navail));
            navail <= navail + 5'd8;
            // NOTE: when navail==0 the shift (8-0)=8 places the byte at [15:8]
         end
         else if (have_bit) begin
            bitbuf <= bitbuf << 1;
            navail <= navail - 5'd1;
            if (match) begin
               out_valid <= 1'b1;
               out_sym   <= dsym_r;
               code <= 0; first <= 0; index <= 0; len <= 4'd1;
            end
            else begin
               code  <= code1 << 1;
               first <= (first + count) << 1;
               index <= index + count;
               len   <= len + 4'd1;
            end
         end
      end
   end

endmodule
'''


def main():
    freq = [max(1, round(1e6 * (0.98 ** s))) for s in range(NSYM)]
    length = huffman_lengths(freq)
    mx = max(length)
    assert mx <= MAXLEN, "max length %d > %d" % (mx, MAXLEN)
    cnt, code, order = canonical(length)
    # sanity: Kraft equality
    kraft = sum(2.0 ** (-length[s]) for s in range(NSYM))
    assert abs(kraft - 1.0) < 1e-9, "kraft %f" % kraft
    open("huffman_enc.v", "w").write(emit_enc(length, code, mx))
    open("huffman_dec.v", "w").write(emit_dec(cnt, order, mx))
    print("max code length =", mx, " kraft =", kraft)
    print("wrote huffman_enc.v, huffman_dec.v")


if __name__ == "__main__":
    main()
