# Yosys synthesis script (TCL) for the LogikBench 'lb' runner.
#
# Run with:  yosys -c synth.tcl
#
# The 'lb' runner generates params.tcl in the run directory, defining:
#   top      top module name
#   fileset  path to the fileset command file (*.f)
#   name     benchmark name (used for output filenames)
#   options  extra synthesis command options (may be empty)
#   part     FPGA part name (may be empty)??
#

# loading wildebeest plugin
yosys plugin -i wildebeest

# name of zeroasic synthesis command
set cmd synth_fpga

# default options for this target (extend as needed); per-run --opt is
set default_options {}

########################################################
# Boiler plate below
########################################################

# Required yosys plugin
yosys plugin -i slang

# Per-benchmark parameters generated by the 'lb' runner
source ./params.tcl

# Read fileset command file (*.f)
yosys read_slang -f $fileset --top $top

# Check design hierarchy and set top module
yosys hierarchy -check -top $top

# FPGA synthesis + technology mapping
yosys $cmd {*}$default_options {*}$options

# Get stats
yosys tee -o ${name}_stats.json stat -json

# Write synthesized netlist as Verilog
yosys write_verilog -noattr ${name}.vg
