#!/usr/bin/env python3
# Generator for a synthesizable parameterizable R2SDF FFT (rtl/fft.v).
# DIF radix-2 single-path delay feedback, per-stage 1/2 scaling, bit-reversed
# output. Twiddle source is a 256-entry sine ROM emitted as a synthesizable
# case (survives --ignore-initial; no initial-block memory load).
import math
import sys

NSIN = 256
DW = 16
maxval = 2 ** (DW - 1) - 1


def sinval(i):
    v = int(round(math.sin(2 * math.pi * i / NSIN) * maxval))
    if v > maxval:
        v = maxval
    if v < -maxval:
        v = -maxval
    return v


def sin_case():
    lines = []
    for i in range(NSIN):
        v = sinval(i)
        if v < 0:
            lines.append("        8'd%d: val = -16'sd%d;" % (i, -v))
        else:
            lines.append("        8'd%d: val = 16'sd%d;" % (i, v))
    return "\n".join(lines)


HEADER = r'''//#############################################################################
// Copyright: Zero ASIC. All rights Reserved.
// License:  MIT (see LICENSE file in LogikBench repository)
//#############################################################################
//
// Parameterizable streaming FFT accelerator.
//
// Architecture: radix-2 decimation-in-frequency (DIF) single-path delay
// feedback (R2SDF). LOG2N pipeline stages, one complex sample in per clock,
// one complex sample out per clock after the pipeline fills. Each stage has a
// butterfly, a feedback delay line (depth N/2^(stage+1)), and a complex
// twiddle multiplier fed by a shared sine ROM.
//
// Scaling: every stage scales its butterfly results by 1/2, so the output is
// the true FFT divided by N (block-scaling that keeps Q1.15 from overflowing).
//
// Output order: natural R2SDF order, i.e. BIT-REVERSED frequency bins.
//
// Data format: Q1.15 signed fixed-point, real and imaginary.
//
// NOTE: This file is generated by genfft.py (twiddle ROM). N must be a power
// of two, 2 <= N <= 256 (the sine ROM has 256 entries).
//
//#############################################################################

module fft
  #(parameter DW = 16,  // data width (Q1.15)
    parameter N  = 64   // FFT size (power of two, <= 256)
    )
   (
    input                  clk,
    input                  rst,        // synchronous, active high
    input                  in_valid,
    input signed [DW-1:0]  in_real,
    input signed [DW-1:0]  in_imag,
    output                 out_valid,
    output signed [DW-1:0] out_real,
    output signed [DW-1:0] out_imag
    );

   localparam LOG2N = $clog2(N);

   // Per-stage streaming buses (LOG2N+1 boundaries: [0]=input .. [LOG2N]=out)
   wire signed [DW-1:0] sr [0:LOG2N];
   wire signed [DW-1:0] si [0:LOG2N];
   wire                 sv [0:LOG2N];

   assign sr[0] = in_real;
   assign si[0] = in_imag;
   assign sv[0] = in_valid;

   genvar s;
   generate
      for (s = 0; s < LOG2N; s = s + 1) begin : g_stage
         fft_bf2sdf #(.DW   (DW),
                      .NP   (N),
                      .LOG2N(LOG2N),
                      .STAGE(s))
         u_stage (.clk      (clk),
                  .rst      (rst),
                  .in_valid (sv[s]),
                  .in_real  (sr[s]),
                  .in_imag  (si[s]),
                  .out_valid(sv[s+1]),
                  .out_real (sr[s+1]),
                  .out_imag (si[s+1]));
      end
   endgenerate

   assign out_real  = sr[LOG2N];
   assign out_imag  = si[LOG2N];
   assign out_valid = sv[LOG2N];

endmodule

//#############################################################################
// One R2SDF stage: butterfly + feedback delay line + twiddle multiply
//#############################################################################
module fft_bf2sdf
  #(parameter DW    = 16,
    parameter NP    = 64,   // full FFT size
    parameter LOG2N = 6,
    parameter STAGE = 0
    )
   (
    input                  clk,
    input                  rst,
    input                  in_valid,
    input signed [DW-1:0]  in_real,
    input signed [DW-1:0]  in_imag,
    output reg             out_valid,
    output reg signed [DW-1:0] out_real,
    output reg signed [DW-1:0] out_imag
    );

   // Feedback delay depth for this stage = NP / 2^(STAGE+1)
   localparam FBLOG = LOG2N - 1 - STAGE;   // log2(depth); MSB of period
   localparam FBDEPTH = (1 << FBLOG);
   // 256-entry ROM step so a twiddle index in [0,NP) maps into [0,256)
   localparam SHIFT256 = 8 - LOG2N;

   // sample counter (position within the N-point frame at this stage)
   reg [LOG2N-1:0] cnt;
   wire            cb = cnt[FBLOG];               // 0=load,1=bfly
   wire [LOG2N-1:0] p = cnt & ((1 << FBLOG) - 1); // index within half

   // feedback shift register (complex), depth FBDEPTH
   reg signed [DW-1:0] fb_r [0:FBDEPTH-1];
   reg signed [DW-1:0] fb_i [0:FBDEPTH-1];
   wire signed [DW-1:0] fbo_r = fb_r[FBDEPTH-1];
   wire signed [DW-1:0] fbo_i = fb_i[FBDEPTH-1];

   integer i;

   // butterfly (scaled by 1/2)
   wire signed [DW:0] sum_r = fbo_r + in_real;    // one extra bit
   wire signed [DW:0] sum_i = fbo_i + in_imag;
   wire signed [DW:0] dif_r = fbo_r - in_real;
   wire signed [DW:0] dif_i = fbo_i - in_imag;
   wire signed [DW-1:0] sum_r2 = sum_r >>> 1;
   wire signed [DW-1:0] sum_i2 = sum_i >>> 1;
   wire signed [DW-1:0] dif_r2 = dif_r >>> 1;
   wire signed [DW-1:0] dif_i2 = dif_i >>> 1;

   // twiddle for the difference path: W_N^(p<<STAGE)
   wire [7:0] addr = (p << (STAGE + SHIFT256));
   wire signed [15:0] cosv, sinv;
   fft_sinrom u_cos (.idx(addr + 8'd64), .val(cosv));   // cos = sin(x+90deg)
   fft_sinrom u_sin (.idx(addr),         .val(sinv));
   wire signed [DW-1:0] wr =  cosv;
   wire signed [DW-1:0] wi = -sinv;
   // complex multiply (dif2 * W), Q1.15
   wire signed [2*DW-1:0] m_rr = dif_r2 * wr;
   wire signed [2*DW-1:0] m_ii = dif_i2 * wi;
   wire signed [2*DW-1:0] m_ri = dif_r2 * wi;
   wire signed [2*DW-1:0] m_ir = dif_i2 * wr;
   wire signed [DW-1:0] tw_r = (m_rr - m_ii) >>> 15;
   wire signed [DW-1:0] tw_i = (m_ri + m_ir) >>> 15;

   // next value written to the delay line
   wire signed [DW-1:0] nd_r = cb ? tw_r : in_real;
   wire signed [DW-1:0] nd_i = cb ? tw_i : in_imag;

   always @(posedge clk) begin
      if (rst) begin
         cnt       <= 0;
         out_valid <= 1'b0;
         for (i = 0; i < FBDEPTH; i = i + 1) begin
            fb_r[i] <= 0;
            fb_i[i] <= 0;
         end
         out_real <= 0;
         out_imag <= 0;
      end
      else begin
         out_valid <= in_valid;
         if (in_valid) begin
            cnt <= cnt + 1'b1;
            // shift the feedback line, inject nd at the head
            for (i = FBDEPTH-1; i > 0; i = i - 1) begin
               fb_r[i] <= fb_r[i-1];
               fb_i[i] <= fb_i[i-1];
            end
            fb_r[0] <= nd_r;
            fb_i[0] <= nd_i;
            // stage output
            if (cb) begin
               out_real <= sum_r2;
               out_imag <= sum_i2;
            end
            else begin
               out_real <= fbo_r;
               out_imag <= fbo_i;
            end
         end
      end
   end

endmodule

//#############################################################################
// Sine ROM module: val = round(sin(2*pi*idx/256)*32767). Combinational case
// (no function, no initial block); instantiated for the sin and cos lookups.
//#############################################################################
module fft_sinrom
  (
   input [7:0]            idx,
   output reg signed [15:0] val
   );
   always @* begin
      case (idx)
'''

FOOTER = r'''
         default: val = 16'sd0;
      endcase
   end
endmodule
'''


def main():
    out = HEADER + sin_case() + FOOTER
    path = sys.argv[1] if len(sys.argv) > 1 else "fft.v"
    with open(path, "w") as f:
        f.write(out)
    print("wrote", path, "(%d bytes)" % len(out))


if __name__ == "__main__":
    main()
