name: Wheels

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Wheels
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: zeroasiccorp/za_logikbench/.github/actions/add@main
      with:
        token: ${{ secrets.ZA_TOKEN }}
        package_name: logikbench

  save:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: Packages
        path: dist

    - name: Add wheels to GitHub release artifacts
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.whl
